### ISSUE TITLE
doesnt seem to work under linux

### ISSUE THREAD

**Issue by ta3pks** [compulim/vscode-mocha#6]
i have following error ![](http://i.imgur.com/z2HTZEK.png)

**Comment by ta3pks** [comment]
i have nodejs installed and working and its on path no other package have problems with that

**Comment by shybyte** [comment]
I have the same problem under Linux.

**Comment by shybyte** [comment]
### How to Fix

In fork.js: 
- Replace `process.env.path`with `(process.env.path || process.env.PATH)`

In findtests.js:
- Replace `require('Glob')` with `require('glob')`

**Comment by ta3pks** [comment]
i think in the main program by switch casing require("os").type() this problem can be easily solved @shybyte

**Comment by ronsrebro** [comment]
@shybyte solution works perfectly on OS X. 

if you're looking for where the files are located see below (from https://code.visualstudio.com/docs/extensions/install-extension):

VS Code looks for extensions under your extensions folder .vscode/extensions. Depending on your platform it is located:

Windows %USERPROFILE%.vscode\extensions
Mac ~/.vscode/extensions
Linux ~/.vscode/extensions

**Comment by ta3pks** [comment]
the latest commit doesnt seem  fixed this issue

**Comment by ta3pks** [comment]
now i dont get those errors @shybyte  but still extension wont work

**Comment by ta3pks** [comment]
no error in the developer tools that is weird

**Comment by cspotcode** [comment]
I have fixed this problem in a fork, published (uncreatively) as "Mocha Latte."  If you install it and uninstall the old "Mocha" extension, this problem should be solved.

https://marketplace.visualstudio.com/items?itemName=cspotcode.vscode-mocha-latte

You can file issues over at [cspotcode/vscode-mocha-latte](https://github.com/cspotcode/vscode-mocha-latte) or file them here and @mention me.

**Comment by flying-sheep** [comment]
@cspotcode you missed the fix for findtests.js mentioned in the original post
